# -*- coding: utf-8 -*-
"""02/25Loop/Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rMjVL9SCyVTzqbQj_X57pftWt8UmXm_k
"""

import pandas as pd
import scipy.stats
xl = pd.ExcelFile("/content/TableauSalesData (1).xlsx")
SalesData = xl.parse("Orders")

JustTables = SalesData.loc[SalesData["Sub-Category"]=="Tables"]
RegJustTablesDiscount = JustTables[["Region", "Discount"]].groupby(by="Region").mean()
print(RegJustTablesDiscount)

JustTablesYear = JustTables.copy()
JustTablesYear["Year"] = JustTablesYear["Order Date"].dt.year
Years = JustTablesYear["Year"].unique()
RegJustTablesYear = JustTablesYear[["Region", "Year", "Discount"]]
for year in Years:
  OneYear = RegJustTablesYear.loc[RegJustTablesYear["Year"]==year]
  YearlyRegDiscount = OneYear.groupby(by="Region").mean()
  print("\n Regional table discounts for the year " + str(year))
  print(YearlyRegDiscount)
  print("*"*40)

JustTablesYear = JustTables.copy()
JustTablesYear["Year"] = JustTablesYear["Order Date"].dt.year
Years = JustTablesYear["Year"].unique()
RegJustTablesYear = JustTablesYear[["Segment", "Year", "Discount"]]
for year in Years:
  OneYear = RegJustTablesYear.loc[RegJustTablesYear["Year"]==year]
  NoYear = OneYear[["Segment", "Discount"]]
  YearlyRegDiscount = NoYear.groupby(by="Segment").mean()
  print("\nRegional table discounts for the year " + str(year))
  print(YearlyRegDiscount)
  print("*"*40)

Regions = JustTables["Region"].unique()
TableSegRegion = JustTables[["Segment", "Region", "Profit", "Sales"]]
for region in Regions:
  TableSegment = TableSegRegion.loc[TableSegRegion["Region"]==region]
  TablesSegProfSales = TableSegment.groupby(by="Segment").sum()
  print("\nTable profits and sales for each customers segment in the " + region + " are as follows:")
  print(TablesSegProfSales)
  print("#"*50)

Years = JustTablesYear["Year"].unique()
Regions = JustTablesYear["Region"].unique()
SegJustTablesYear = JustTablesYear[["Segment", "Year", "Discount", "Region"]]
for year in Years:
  OneYear = SegJustTablesYear.loc[SegJustTablesYear["Year"]==year]
  NoYear = OneYear[["Segment", "Discount", "Region"]]
  for region in Regions: 
    OneRegion = NoYear.loc[NoYear["Region"]==region]
    YearlySegRegDiscount = OneRegion.groupby(by="Segment").mean()
    print("\n" + str(year) + " Table discounts by segment in the " + region + "region")
    print(YearlySegRegDiscount)
    print("#"*50)